### ISSUE TITLE
The dashboard broken with ledger address

### ISSUE THREAD

**Issue by Yug-Damon** [RealToken-Community/dashboard-v2#55] opened 2024-06-28 16:02 UTC
Hello,

I was successfully using the dashboard for the past weeks, here the context:
- **Browser**: Google Chrome
- **Wallet**: Metamask
- **Account**: Hot Wallet (mnemonic, no passphrase)
- I'm was connected the website with gnosis chain + my properties account (hot wallet).
- The wallet appears connected in the interface. The address was visible

I recently moved all my tokens to a new account (with the help of realt.co support), and then the dashboard ceased to work.

Here some informations about the context when the issue occurs:
- **Browser**: Google Chrome
- **Wallet**: Metamask
- **Account**: Cold storage (Ledger Nano X)
- I'm well connected the website with gnosis chain + my property account (ledger).
- The wallet appears connected in the interface "Déconnecter mon porte feuille"

Browser console : 

`Could not fetch ENS names Error: network does not support ENS (operation="lookupAddress", network="xdai", code=UNSUPPORTED_OPERATION, version=providers/5.7.2)
    at h.makeError (_app-5f653515702f16ea.js:1:66309)
    at h.throwError (_app-5f653515702f16ea.js:1:66429)
    at St.<anonymous> (_app-5f653515702f16ea.js:1:110500)
    at Generator.next (<anonymous>)
    at s (_app-5f653515702f16ea.js:1:82570)`

`Error in event handler: Error: write after end
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:19:30103
  at y.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:19:30166)
  at i.d (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:10:75622)
  at a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:10:32942)
  at U (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:10:69332)
  at F (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:10:69062)
  at B.push (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:10:69662)
  at i._onMessage (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:10:35414)
  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/contentscript.js:10:35210`

`Access to fetch at 'https://api.thegraph.com/subgraphs/name/realtoken-thegraph/realtoken-xdai' from origin 
'https://dashboard.realt.community' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

`_app-5f653515702f16ea.js:1 
 POST https://api.thegraph.com/subgraphs/name/realtoken-thegraph/realtoken-xdai net::ERR_FAILED`

`ApolloError
    at new t (_app-5f653515702f16ea.js:1:1334074)
    at _app-5f653515702f16ea.js:1:1401985
    at r (_app-5f653515702f16ea.js:1:1353485)
    at _app-5f653515702f16ea.js:1:1353410
    at new Promise (<anonymous>)
    at Object.then (_app-5f653515702f16ea.js:1:1353376)
    at Object.error (_app-5f653515702f16ea.js:1:1353495)
    at F (_app-5f653515702f16ea.js:1:1316469)
    at z (_app-5f653515702f16ea.js:1:1316926)
    at t.error (_app-5f653515702f16ea.js:1:1317511)`

Thank you for your time

**Comment by drbruddet** [comment] 2024-07-03 17:55
Same here with ApolloError. (address on Rabby, ledger backed). I also tried reset caches, safari / brave / chrome browser, and also I tried to find another wallet address on a property and open a dashboard in view only with this address which is not mine, and the problem is also here (so it's not coming from my eth addr). 

here are more details:
If I'm looking on the network, I get 
https://api.thegraph.com/subgraphs/name/realtoken-thegraph/realtoken-xdai
`Request Method:
POST
Status Code:
410 Gone`

And the operationName in the payload :  **"GetUserIdQuery"**.

I think they changed the api and there is a new api path.

Thanks

**Comment by NandyBa** [comment] 2024-08-15 15:29
Hi do you still have the issue ?

**Comment by Yug-Damon** [comment] 2024-08-15 15:37
Hello, I've recently noticed the issue being solved, thank you

**Comment by NandyBa** [comment] 2024-08-15 22:23
Ok @Yug-Damon, so I will close this issue, feel free to open a new one if similar issue happened
Have a good day / night depending of your timezone !

**Closed by NandyBa** 2024-08-15 22:23 UTC
